name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@0.11.2
    with:
      dotnet-logging: ${{ inputs.dotnet-logging }}
      dotnet-version: |
        6.x
        7.x
        8.x
      solution: ./SequentialGuid.sln
    secrets: inherit
